service: clamio-backend

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024 # Customize based on your app needs
  timeout: 30 # In seconds, adjust as necessary
  environment:
    SESSION_SECRET: ${env:SESSION_SECRET}
    SESSION_TABLE: sessionTable  # DynamoDB table for session storage

functions:
  api:
    handler: dist/lambda.handler # Handler from webpack output
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.ts'
    includeModules: true
