import { Schema,Prop,SchemaFactory } from "@nestjs/mongoose";
import { HydratedDocument ,Types} from "mongoose";


export type UserDocument=HydratedDocument<User>

export class User{
    //id will generated by mongodb (_id)

    @Prop({required : true})
    username:string

    @Prop({required : true})
    email:string

    @Prop({required : false})
    password:string

    @Prop({required:false})
    bio : string

    @Prop({required : true})
    profile_picture : string

    @Prop ({required : true})
    creator : Boolean


}

export const UserSchema=SchemaFactory.createForClass(User);