import { Schema, Prop, SchemaFactory } from "@nestjs/mongoose";
import { HydratedDocument, Types } from "mongoose";

export type WishlistDocument = HydratedDocument<Wishlist>;

@Schema()
export class Wishlist {
    //wishlist id should be generated by mongodb (_id)


    @Prop({ required: true, type: Types.ObjectId, ref: 'User' })
    user_id: Types.ObjectId;

    @Prop({ required: true, type: Types.ObjectId, ref: 'Product' })
    product_id: Types.ObjectId;
}

export const WishlistSchema = SchemaFactory.createForClass(Wishlist);
