import {
  attribute,
  hashKey,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';

@table('bookService')
export class BookService {
  @autoGeneratedHashKey() // Auto-generated ID
  _id: string;

  @attribute() // ID of the order
  order_id: string;

  @attribute() // ID of the user who booked the service
  user_id: string;

  @attribute() // ID of the service that was booked
  service_id: string;

  @attribute() // Date of purchase
  purchase_date: Date;

  @attribute() // Price paid for the service
  price_paid: number;

  @attribute() // Status of the service (e.g., pending, completed)
  status: string;

  @attribute() // Nested data object for additional details
  Data: {
    DOB: string; // Date of birth
    full_name: string; // Full name of the user
    birth_time: string; // Time of birth
  };
}
