import { hashKey, attribute, table, autoGeneratedHashKey } from "@aws/dynamodb-data-mapper-annotations";



export class Product {
    @attribute()
    product_id: string;

    @attribute()
    quantity: number;

    @attribute()
    price: number;

    @attribute()
    added_at: Date;

    @attribute()
    product_url: string;

    @attribute()
    creator_id: string;

    @attribute()
    creator_name: string;

    constructor(
        product_id: string,
        price: number,
        added_at: Date,
        product_url: string,
        creator_id: string,
        creator_name: string
    ) {
        this.product_id = product_id;
        this.quantity = 1;
        this.price = price;
        this.added_at = added_at;
        this.product_url = product_url;
        this.creator_id = creator_id;
        this.creator_name = creator_name;
    }
}


@table('cart')
export class Cart {
    @hashKey()
    _id: string;

    @attribute()
    user_id: string;

    @attribute() // Correcting the type for 'products' as an array of 'Product'
    products: Product[];

    @attribute()
    total_amount:number;
}
