import {
  attribute,
  hashKey,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';

@table('dietPlan')
export class DietPlan {
  @autoGeneratedHashKey() // Auto-generated ID
  _id: string;

  @attribute() // URL of the diet plan product
  product_url: string;

  @attribute() // ID of the creator of the diet plan
  creator_id: string;

  @attribute() // Date the diet plan was created
  created_date: Date;

  @attribute() // Title of the diet plan
  title: string;

  @attribute() // Description of the diet plan
  description: string;

  @attribute() // Enum array representing diet plan categories
  category: string[];

  @attribute() // Price of the diet plan
  price: number;

  @attribute() // Thumbnail URL for the diet plan
  thumbnail_url: string;

  @attribute() // URL of the diet plan file
  file_url: string;

  @attribute() // Type of content file (e.g., PDF, DOC)
  content_file_type: string;

  @attribute() // Average rating of the diet plan
  avg_rating: number;

  @attribute() // ID of the review
  review_id: string;

  @attribute() // Nested data object for user-specific health information
  Data: {
    weight: number; // User's weight
    height: number; // User's height
    age: number; // User's age
    Name: string; // User's name
    allergy_illness_history: string; // User's allergy/illness history
    purpose: string; // Purpose of the diet plan
    description: string; // Additional description of the diet plan
  };

  @attribute() // Custom questions for the diet plan with a limit of 10
  custom_questions: {
    question_1?: string;
    question_2?: string;
    question_3?: string;
    question_4?: string;
    question_5?: string;
    question_6?: string;
    question_7?: string;
    question_8?: string;
    question_9?: string;
    question_10?: string;
  };
}
