import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('digitalArt')
export class DigitalArt {
  @autoGeneratedHashKey() // Auto-generated ID
  _id: string;

  @attribute() // URL of the digital art product
  product_url: string;

  @attribute() // ID of the creator of the digital art
  creator_id: string;

  @attribute() // Date the digital art was created
  created_date: Date;

  @attribute() // Title of the digital art
  title: string;

  @attribute() // Description of the digital art
  description: string;

  @attribute() // Enum array representing digital art categories
  category: string[];

  @attribute() // Price of the digital art
  price: number;

  @attribute() // Thumbnail URL for the digital art
  thumbnail_url: string;

  @attribute() // URL of the digital art file
  images_url: string;

  @attribute() // Type of content file (e.g., PNG, JPG)
  content_file_type: string;

  @attribute() // Average rating of the digital art
  avg_rating: number;

  @attribute() // ID of the review
  review_id: string;

  @attribute() // Nested data object for additional details
  Data: {
    mainPhoto: string; // Main photo
    additionalPhoto: string; // Additional photo
    dress: string; // Dress details
    description: string; // Description (100 words)
    full_name: string; // Full name
  };

  @attribute() // Custom questions with a limit of 10
  custom_questions: {
    question_1?: string;
    question_2?: string;
    question_3?: string;
    question_4?: string;
    question_5?: string;
    question_6?: string;
    question_7?: string;
    question_8?: string;
    question_9?: string;
    question_10?: string;
  };
}
