import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('serviceAssignmentList')
export class ServiceAssignmentList {
  @autoGeneratedHashKey() // Auto-generated ID
  _id: string;

  @attribute() // ID of the order associated with the service assignment
  order_id: string;

  @attribute() // ID of the user who purchased the service
  user_id: string;

  @attribute() // ID of the assigned service
  service_id: string;

  @attribute() // Date the service was purchased
  purchase_date: Date;

  @attribute() // Price paid for the service
  price_paid: number;

  @attribute() // Status of the service assignment (e.g., active, completed)
  status: string;

  @attribute() // PDF associated with the service assignment
  pdf?: string; // Optional field, can store URL or base64 string for the PDF file
}
