import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('tarotCardReading')
export class TarotCardReading {
  @autoGeneratedHashKey() // Auto-generated ID for the service
  service_id: string;

  @attribute() // ID of the creator
  creator_id: string;

  @attribute() // URL of the tarot card reading product
  product_url: string;

  @attribute() // Title of the tarot card reading service
  title: string;

  @attribute() // Description of the service
  description: string;

  @attribute() // Price of the service
  price: number;

  @attribute() // Average rating of the service
  avg_rating: number;

  @attribute() // ID of the review
  review_id: string;

  @attribute() // Date the tarot card reading service was created
  created_date: Date;

  @attribute() // Category, specifically for Tarot Cards
  category: string; // You can use an enum for TarotCard

  @attribute() // Slots for tarot card readings
  slots: string[];

  @attribute() // Reading for a specific year, month, and day
  read_for: string; // Year-Month-Day format

  @attribute() // Nested data object for additional details
  Data: {
    DOB: string; // Date of birth
    full_name: string; // Full name of the user
    birth_time: string; // Time of birth
    description: string; // Description provided by the user
  };

  @attribute() // Custom questions with a limit of 10
  custom_questions: {
    question_1?: string;
    question_2?: string;
    question_3?: string;
    question_4?: string;
    question_5?: string;
    question_6?: string;
    question_7?: string;
    question_8?: string;
    question_9?: string;
    question_10?: string;
  };
}
