import {
  attribute,
  hashKey,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';

@table('user') // This should match the DynamoDB table name
export class user {
  @autoGeneratedHashKey() //id will be auto generated
  _id: string;

  @attribute() // email is required for every user
  email: string;

  //username is optional field, if user login with google then we will get name otherwise not
  @attribute()
  username: string;

  //password is an optional field , if user login with google we don't get password
  @attribute()
  password?: string;

  //firstname is an optional filed
  @attribute()
  firstname?: string;

  //lastname is an optional filed
  @attribute()
  lastname?: string;

  @attribute()
  profilePicture?: string;

  @attribute()
  createdAt: Date;
}
